export const ARTWORK_UPLOAD_COPY = {
  heading: 'Add an artwork',
  message: 'Photograph an artwork or choose one from Photos to add it to your Musee library.',
  takePhoto: 'Take a Photo',
  choosePhoto: 'Choose from Photos',
  usePhoto: 'Upload to Musee',
  labelAttached: 'Label attached · used for identification only',
  chooseDifferentPhoto: 'Choose a different photo',
  uploadAnother: 'Upload another artwork',
  openLibrary: 'Open Library',
  analyzingHeading: 'Analyzing artwork',
  connectingMessage: 'Musee is preparing the artwork for analysis…',
  receivingMessage: 'Identifying the artist and artwork…',
  analyzedStatus: 'Analysis complete',
  retryUpload: 'Try upload again',
  retryAnalysis: 'Try analysis again',
  uploadingToast: 'Uploading artwork…',
  analyzingToast: 'Analyzing artwork…',
  analyzedToast: 'Artwork analysis complete',
  rejectedPhotos: 'Some selected photos could not be prepared.',
  noUsablePhotos: 'Musee could not prepare the selected photos. Choose different images.',
  batchFailed: 'Musee could not add the selected artworks.',
} as const;
