export const CAMERA_COPY = {
  close: 'Close',
  closeSymbol: '×',
  permissionHeading: 'Camera access is off',
  permissionMessage: 'Allow Musee to use the camera so you can capture an artwork.',
  enableCamera: 'Enable Camera',
  openSettings: 'Open Settings',
  unavailableHeading: 'Camera unavailable',
  unavailableMessage: 'The camera is not available on this device. You can still choose a photo.',
  choosePhoto: 'Choose from Photos',
  retake: 'Retake',
  usePhoto: 'Continue',
  nextArtwork: 'Take artwork',
  artwork: 'Artwork',
  label: 'Label',
  optional: 'Optional',
  captured: 'Captured',
  takeArtwork: 'Capture artwork',
  takeLabel: 'Capture label',
  previewArtwork: 'Artwork preview',
  previewLabel: 'Label preview',
  retrySave: 'Try saving again',
  continueWithoutSaving: 'Continue without saving',
  captureError: 'Musee could not take this photo. Please try again.',
  saveError: 'Musee could not save this photo to Photos. You can continue without saving it.',
} as const;
